- examples/stop_application_on_unfocus.py
- i3ipc.py
PEP8 cleanup and add an useful script to help save battery when running browsers.
> Add example stop_application_on_unfocus.py

- i3ipc.py
Window instance attribute is very useful for matching againts e.g. Chrome windows.
> Add window_instance attribute

- i3ipc.py
This is useful when handling workspace change events.
> Added workspace "num" attribute to Con object.

- i3ipc.py
This also allows the user to specify a socket path from Python. This library works on [sway](https://github.com/SirCmpwn/sway) with this patch applied.
> Obey the I3SOCK environment variable

- i3ipc.py
floating_nodes is currently only an empty list.
> Bugfix floating nodes

- i3ipc.py
https://xkcd.com/859/
I guess this is the way it was intended…
> Fix command_children

- i3ipc.py
The recv() syscall is interrupted if, e.g., the process receives a
signal. With this PR, we try to recv() again if recv() was interrupted.
(This is the idiomatic way to deal with interruptions.)
> Make socket.recv() robust against interruptions

- i3ipc/i3ipc.py
This exposes the gaps information in i3-gaps in i3ipc if it is available. After writing this I noticed that i3 is only exposiing the deviation from the value in the config file so I am not sure how usful it is to anyone.
> added the abaility to get the current window gaps.

- i3ipc/i3ipc.py
> Use native byte order everywhere

- i3ipc/i3ipc.py
Fixed a bug that prevented finding floating containers. This was introduced in c4d9ee4b when Con was made into an iterator.
> Fix floating nodes.

- i3ipc/i3ipc.py
> Teardown socket when main function ends

- i3ipc/i3ipc.py
- test/test_get_bindings_modes.py
- test/test_get_config.py
- test/test_get_marks.py
Tell me if you need tests for any of these
> Implement missing messages

- i3ipc/i3ipc.py
- test/test_ticks.py
Adds the send_tick message and the tick event.
For info see:
- https://github.com/i3/i3/pull/3005
- https://i3wm.org/docs/ipc.html#_tick_reply
- https://i3wm.org/docs/ipc.html#_tick_event
Subscription will fail without https://github.com/i3/i3/pull/3271
> Implement ticks

- i3ipc/i3ipc.py
No test because the sticky command requires an actual window to be
successful.
> Add sticky property

- docs/index.rst
- i3ipc/i3ipc.py
> Added title attribute to Con objects

- examples/i3-cycle-focus.py
Hopefully, I didn't miss any changes :grinning:
> examples: update i3-cycle-focus.py for recent api changes

- examples/i3-focus/history-server.py
Bug fix for window jump to closed window
> examples/i3-focus: Remove window id from history on close

- i3ipc/con.py
> Add sway 'visible' attribute to 'Con'

- i3ipc/aio/connection.py
This is done by adding them to a set and removing them when the task
is done. asyncio itself only keeps a weak references to all tasks. A
task can therefore be destroyed when it is not referenced anymore.
When this happens, we get things like that:
```
task: <Task pending name='Task-326' coro=<_AIOPubSub.queue_handler.<locals>.handler_coroutine() done, defined at /usr/lib/python3/dist-packages/i3ipc/aio/connection.py:30> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9f08a13be0>()]>>
```
This seldomly happens and I still have a hard time understanding the
exact cause.
To workaround that, we provide a tiny wrapper around `ensure_future()`
keeping a reference to the task and removing it once it is done. In
`connection.py`, all `ensure_future()` produces a task.
> aio: keep references on tasks created by ensure_future

- examples/app-on-ws-init.py
Following this link results to 404 Error: File not found
> Remove dead link in comment of example
