setup.py

As this project aims at Python2 (and <3.4) compatibility, I added a `version_info` check to add the correct and minimal `install_requires`.
Also, a link in the help comments was broken; fixed that too.

Fixes dependencies and a broken link in setup.py

---

examples/app-on-ws-init.py

Make the help message a bit clearer and provides an example.
Relates to https://github.com/acrisci/i3ipc-python/issues/11

Make the 2 mandatory parameters mandatory.

---

i3ipc.py

To be able match windows on the window_role property. Useful for example when working with multiple terminals with different roles.

Add support for window_role

---

i3ipc.py

Need this for a scratchpad segment in powerline/powerline#1542. The key is required to identify currently-visible scratchpad windows as such (they are indistinguishable from floating windows otherwise)

Add 'scratchpad_state' to properties

---

i3ipc.py
setup.py

The state of Xlib/XCB Python bindings is dismal.
python-xlib/python3-xlib are simply broken with recent RandR versions.
xpyb, which is the default XCB Python binding, is very out of date and
doesn't have a proper Python 3 support (upstream state is "untested").
xcffib doesn't provide as wide coverage as xpyb, but supports Python3
and can be considered almost usable, but there are still some issues
and it requires Haskell toolchain in order to be built.
Thus drop all the code that interacts with Xlib.
Instead, retrieve the IPC socket path directly from i3.
Call i3 with the `--get-socketpath' command-line option, which is
available since v4.1 release, to retrieve the i3 IPC socket path.

Remove interactions with Xlib and python3-xlib dependency

---

i3ipc.py

Hey,
I am not sure, if this is the correct way to deal with this, but for me i3ipc.Connection() gave me the following error:
```
In [5]: i3 = i3ipc.Connection()
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-b86818f0fd4c> in <module>()
----> 1 i3 = i3ipc.Connection()
/home/hendrik/dev/evasive-window/i3ipc.py in __init__(self, socket_path)
187         print(self.socket_path)
188         self.cmd_socket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
--> 189         self.cmd_socket.connect(self.socket_path.rstrip())
190 
191     def _pack(self, msg_type, payload):
FileNotFoundError: [Errno 2] No such file or directory
```
It seems like there is a newline at the end …

Remove newlines from socket path

---

i3ipc.py

In newer versions of i3 containers can have multiple marks, so the property
name has changed from mark to marks.

Change Con.mark to marks

---

i3ipc.py

I needed deco_rect for a script and saw that it was not yet implemented in i3ipc.py (older versions of i3 don't have the properties - at least deco_rect - so I enclosed it in if blocks).

Add window_rect and deco_rect props if available

---

setup.py

I want to package i3ipc-python for Fedora, but it fails to build within rpmbuild, because it sets LANG=C and setup.py fails to read the readme file. This should fix it.

Explicitly set encoding of readme in setup.py

---

examples/command-on-exit.py
i3ipc.py

really fix #42: emit 'ipc_shutdown' instead of 'ipc-shutdown'
also update command-on-exit example

bugfix: fix ipc-shutdown emission + update example

---

i3ipc/__init__.py
setup.py

i3ipc [is a package now](0e42da86b6918c8f7c1df70bcad1c630007d4890), so setup.py requires using packages instead of
py_modules.
Added from .i3ipc import * in the package's __init__.py to keep
backwards compatibility and not require an import like `from i3ipc
import i3ipc`.

fixed setup.py and package

---

i3ipc/i3ipc.py

The default mode 'strict' raises a UnicodeDecodeError on invalid UTF-8 data and crashes the main loop.
Background:
I've that that happen with unicode characters in mpv window titles. Since I use i3ipc for an i3bar status script the crashed main loop (which I run in a daemon thread, thus no crash of the script. the following is speculation:) causes the connection buffer to fill up and i3 to go into an infinite loop/locking up.

Robustness towards UTF-8 decoding errors

---

i3ipc/i3ipc.py

Set the floating attribute that is sent from i3 inside the Con class so users can differentiate between floating and non-floating windows.

Set floating attribute on Con class

---

i3ipc/i3ipc.py
run-tests.py
test/ipctest.py

In Python 2 default encoding for unicode.encode() is 'ascii'. This PR fixes unicode encoding issue. It also fixes test runner and tests for Python 2.
Reproducing a bug:
```
>>> import i3ipc
>>> i3 = i3ipc.Connection()
>>> i3.command(u'rename workspace 1 to 1:🌐')
...
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f310' in position 24: ordinal not in range(128)
```

Fix unicode support in Python 2

---

i3ipc/i3ipc.py

Con.command was not properly returning the error status.
This patch fixes it.

fix missing return statement in Con.command

---

examples/focused-windows.py
i3ipc/i3ipc.py

i3 provides information about the focus inside a container as a
list of its children's id, where the first element refers to the
childern with (in)active focus. This information is now available
as focus attribute.

Add focus attribute.

---

examples/asyncio-i3status-wrapper.py
i3ipc/i3ipc.py

Split `main()` into 3 methods in order to make it easier to use i3ipc from external event loops, such as the one provided by asyncio.
Also show how to use with asyncio by adding an example that reads data from i3status and the IPC socket in parallel.
Note that it is already possible to use i3ipc from asyncio by running `i3ipc.main()` in a separate thread, but since python cannot run multiple threads efficiently due to GIL, I think this makes a good enhancement.

Allow usage from external event loops.

---

examples/workspace_renumber.py

Moves windows on workspaces that are out of order to the lowest number workspace available so for example if you have one window open on workspace 1 then move to workspace 8 and open a new window(application), when focus changes the window on workspace 8 would be moved to workspace 2 so you can always count on windows being on consecutive workspaces
This is useful for example when you want to replace what polybar shows for i3 windows from the default number index to custom icons.  It ensures you don't have to guess what number to use when switching workspaces as they will always be numbered from 1 onwards

Add script that makes sure workspace numbers are always consecutive

---

examples/tiling-indicator.py

Hi!
Inspired by [this](https://www.reddit.com/r/i3wm/comments/75k5eq/add_tiling_direction_indicator_to_i3bar/) I wrote a small script that simply outputs whether the current container is set to vertical or horizontal tiling.
Maybe it's of use to someone else!
Cheers.

added tiling-indicator example

---

examples/i3-cycle-focus.py

Kind of related to #50, I extended the script *focus-last.py* to be able to cycle through all previously focused windows.
I wanted to emulate the `Alt-Tab` behaviour of other window managers like Openbox. But i3 doesn't allow to trigger an action when the `Alt` key is released.
So I use a timer to update the focus history after a certain span of time after a new window has been focused.
The previous behaviour of the script (toggling between the current and the previously focused window) can be restored by setting `--delay 0.0`.

i3-cycle-focus.py: cycle through all previously focused windows

---

i3ipc/i3ipc.py

`Timer.start()` returns None. `timer` was always `None` and never got cancelled.

Fix: timer is always None

---

.travis.yml

Trying to follow [these instructions](https://i3wm.org/docs/repositories.html) to get the latest development i3 to run for the tests on travis.

travis: use development i3

---

examples/floating-mode.py

this is the solution to a thing that have bugged me in i3 for a long time.
I have a global rule set to make all new windows floating:  
`for_window [class="^.*"] floating enable`  
But i3 triggers this rule after the config is reloaded and the **title** of a window changes (which happens when you change tab in the browser or file in the editor fi). I thought i add it as an example script. 
Thanks for a great tool!
https://github.com/i3/i3/issues/3628  
https://old.reddit.com/r/i3wm/comments/85ctji/when_windows_are_floating_by_default_how_do_i/  
(*i am not the reddit user. *)

added floating-mode example script

---

i3ipc/i3ipc.py

I don't know if its documented, but sway has a pid property for windows, added [here](https://github.com/swaywm/sway/pull/2676).

Add pid property for sway

---

examples/nth_window_in_workspace.py

Implements #102 the program also switches to mode "default" unless the fourth argument is specified, in which case, unless it is `"no"` it switches to the given mode. In line with the key-to-window mapping is probably in some mode. There is also an option to only switch to visible windows.

Nth window in workspace

---

i3ipc/connection.py

This is the exact same thing that `i3 --get-socketpath` does, it's just this doesn't require a subprocess call. I also removed the sway subprocess call as we already do what `sway --get-socketpath` does above by getting $SWAYSOCK.

Use more direct methods of getting the socket path

---

i3ipc/connection.py
i3ipc/model.py

Sway has its specific command types `IPC_GET_INPUTS` and `IPC_GET_SEATS`.

Add sway-specific commands

---

examples/focus-last.py

In the current version , the window event (https://i3ipc-python.readthedocs.io/en/latest/events.html#i3ipc.Event.WINDOW) emits Con=<class 'i3ipc.con.Con'>
Con doesn't have a 'props' attribute:
https://i3ipc-python.readthedocs.io/en/latest/aio-con.html#i3ipc.aio.Con
I'm assuming that the variable 'id' on 'Con' would be representative

'Con' has no attribute 'props'

---

MANIFEST.in

The tests depend on test/i3.config
examples and docs are helpful to redist to users.

MANIFEST.in: Fix tests, add examples and docs

---

examples/i3-cycle-focus.py

- add on_shutdown() handler;
- needs to be coupled with the daemon process being started from i3
config using exec_always; this makes sure old process, referring to
stale connection upon i3 restart/crash, gets cleaned up.

i3-cycle-focus: kill on i3 'shutdown' event

---

i3ipc/replies.py

The new models omitted some Sway specific output i tems. These are mostly related to the hardware behind the outputs and are the only way to get this info under Sway (xrandr lists XWAYLAND[N])
This pull request adds the missing items.

Add Sway specific fields to OutputReply() model

---

examples/focus-last.py

Create the path to socket portably and such that when script is used
with multiple sessions by the same user or various users each session
gets its own socked which other users can not access.
This is achieved by using UID and DISPLAY in the path name, using the
tempfile module from stdlib to get the path for /tmp, and creating the
socket under a directory which was created with #o700 perms.

examples/focus-last.py: handle multiple sessions and/or users safely

---

examples/i3-focus/focus-app.py
examples/i3-focus/focus-current-app-window.py
examples/i3-focus/history-server.py
examples/i3-focus/tools/__init__.py
examples/i3-focus/tools/app.py
examples/i3-focus/tools/lists.py
examples/i3-focus/tools/menu.py
examples/i3-focus/tools/sockets.py

i3 get_tree does not contain information about focus throw all workspaces, so scripts those use it can sort windows only with workspace grouping.
So server in this PR accumulates window focus history and does not pay attention on workspaces. And focus-app.py switches apps and focus-current-app-window.py switches windows in current app (like in macOS)

Server and window switchers those do not pay attention on workspaces

---

i3ipc/con.py

Add a way to find a container based on pid.
```python
In [1]: import i3ipc                                               
In [2]: i3 = i3ipc.Connection()                                    
In [3]: x = i3.get_tree().find_by_pid(1337)                        
In [4]: x.pid                                                      
Out[4]: 1337
```

add find_by_pid

---

i3ipc/model.py

Newer versions of i3-gaps allow setting the outer gaps on each side of the screen separately. This pull request adds this information to the gaps reply.

Add side-specific outer gap information

---

examples/i3-focus/focus-window.py
examples/i3-focus/history-server.py
examples/i3-focus/tools/app.py
examples/i3-focus/tools/lists.py
examples/i3-focus/tools/menu.py

- fix for non window containers in list
- app title now based on window class instead of window title based
- add index in title for windows with same titles
- add script for flat window selection (without app grouping)
- remove needless comments

i3-focus example fixes

---

examples/nth_window_in_workspace.py

Been other code with this functionality, but didn't realize i hadn't pull-requested it. However, it's better to modify this file i think.
The commandline argument `nth` can be an integer, working as before, it can be `c`/`cycle` in which case if you're already in that workspace, it cycles you through it. (`r`/reverse` goes backwards)
This is basically so you can use a button to go to a workspace, and you can just hit the same button some more to get the right window. (i.e. the button doesn't go useless if you're already on the workspace)

Extend `nth_window_in_workspace.py` to be able to cycle aswel

---

examples/i3-cycle-focus.py

Use only active outputs. Compare workspaces by name.

i3-cycle-focus: small fixes

---

i3ipc/_private/sync.py
i3ipc/aio/connection.py
i3ipc/connection.py
setup.py
test/aio/window.py

Addresses #198. 
This was a feature released in 1.3.0 (see changelog), but then regressed by a merge request in 2.0.1, #116 
Someone must have realized that this replacement method was a bad idea, because the current branch is back to using the `i3/sway --get-socketpath` method. This revert was however incomplete, as the method added to #116 still remains, along with the `python-xlib` dependency. 
Anyhow, the pull request purges any use of `python-xlib`. It's still used in testing, but there the package is separately installed when creating the docker testing image. 
TL;DR: Don't accept pull request by script kiddies that address non-existent issues, regress features, and add package dependencies; all in the name of "removing a subprocess call" by replacing it with 5 method calls to …

Removed superfluous python-xlib dependency
